version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    ports:
      - '${POSTGRES_EXPOSE_PORT}:5432'
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql